config/routes.rb
Rails.application.routes.draw do

  get 'profile/edit/:id', to: 'profile#edit', as: 'profile_edit'

  patch 'profile/update/:id', to: 'profile#update', as: 'profile_update'

  get 'profile/view/:id', to: 'profile#view', as: 'profile_view'

  get 'profile/list/:id', to: 'profile#list', as: 'profile_list'

  get '/search', to: 'search#search', as: 'search'

  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'public_site#index'

  get '/contact', to: 'public_site#contact'

  get '/about', to: 'public_site#about'

  get '/pricing', to: 'public_site#pricing'

  get '/demo', to: 'public_site#demo'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
#
class Address < ApplicationRecord
  def self.postal_code_regex
    /\A[A-Za-z]\d[A-Za-z] ?\d[A-Za-z]\d\z/i
  end
  belongs_to :province
  has_many :users
  validates_associated :province
  validates :city, :street, :street_number, presence: true
  validates :postal_code, format: { with: postal_code_regex,
                                    message: 'Invalid postal code' }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arena.rb
#
class Arena < ApplicationRecord
  validates :name, :address, presence: true
  validates :court_identifier,
            uniqueness: { scope: :address,
                          message: 'Needs to be a unique identifier' }
  belongs_to :address
  validates_associated :address
  has_many :games
end

app/models/country.rb
#
class Country < ApplicationRecord
  has_many :provinces
  validates :name, :abbreviation, presence: true
  validates :abbreviation, uniqueness: { scope: :name }
end

app/models/game.rb
#
class Game < ApplicationRecord
  validates :date, presence: true
  # consider dropping sport (retrievable through association)
  belongs_to :arena
  belongs_to :league
  belongs_to :sport
  validates_associated :arena
  validates_associated :league
end

app/models/league.rb
#
class League < ApplicationRecord
  validates :name, :age_min, :male, :female, presence: true
  # consider dropping sport (retrievable through association)
  belongs_to :official_association
  belongs_to :sport
  validates_associated :official_association
  validates_associated :sport
  has_many :games
end

app/models/official_association.rb
#
class OfficialAssociation < ApplicationRecord
  validates :name, :acronym, :sport, presence: true
  belongs_to :sport
  validates_associated :sport
  has_many :leagues
  has_many :users
end

app/models/province.rb
#
class Province < ApplicationRecord
  belongs_to :country
  has_many :addresses
  validates_associated :country
  validates :name, :abbreviation, presence: true
  validates :abbreviation, uniqueness: { scope: [:name, :country] }
end

app/models/site_content.rb
#
class SiteContent < ApplicationRecord
  validates :content, :page, :index, presence: true
  validates :index, uniqueness: { scope: :page }
  before_create do
    renderer = Redcarpet::Render::HTML.new(filter_html: false, no_image: false,
                                           no_links: false)
    markdown = Redcarpet::Markdown.new(renderer)
    self.content = markdown.render(content)
  end
end

app/models/site_image.rb
#
class SiteImage < ApplicationRecord
  validates :image, :alt, presence: true
  mount_uploader :image, AvatarUploader
end

app/models/sport.rb
#
class Sport < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :official_association
  has_many :games
  has_many :leagues
end

app/models/user.rb
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :address
  belongs_to :official_association
  validates_associated :address

  validates :name, presence: true
  validates :active, :permission, :association_fees_paid,
            presence: true, on: :update

  def not_set(field)
    field.nil? || field.empty?
  end

  before_create do
    self.official_association ||= OfficialAssociation.find_by(name: 'none')
    self.permission             = 0 if not_set games_reffed
    self.active                 = false if active.nil?
    self.association_fees_paid  = false if association_fees_paid.nil?
    self.games_reffed           = 0 if not_set games_reffed
    self.games_cancelled        = 0 if not_set games_cancelled
    self.games_missed           = 0 if not_set games_missed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/profile_controller.rb
#
class ProfileController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def view
    @user = User.find(params[:id])
  end

  def list
    params[:page] ||= 1
    @users = User.where(official_association:
                        OfficialAssociation.find(params[:id]))
                 .page(params[:page]).per(20)
  end

  def update
    @user = User.find(params[:id])
    @user.save!
    redirect_to "/profile/view/#{params[:id]}"
  end
end

app/controllers/search_controller.rb
#
class SearchController < ApplicationController
  def search
    @raw_query = params[:query]
    @query = "%#{@raw_query}%"
    @sport = Sport.where('name like ?', @query)
    @refs = User.where('name like ? or email like ?', @query, @query)
    @associations = OfficialAssociation.where('name like ? or acronym like ?',
                                              @query, @query)

    # @refs << User.where(official_association: @associations)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/public_site_helper.rb
module PublicSiteHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"
    title
      | PlaceholderScheduler
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = render partial: 'shared/navbar'
  .container.body-content
    = yield
  .container
    - flash.each do |key, value| 
    /div class: alert alert-<%= key %>">
      = value

app/views/shared/_address_edit.html.slim
= form_for :address do |addr_f|
  = addr_f.label :street, class: 'form-label'
  br
  = addr_f.text_field :street, class: 'form-control'
  br
  = addr_f.label :street_number, class: 'form-label'
  br
  = addr_f.text_field :street_number, class: 'form-control'
  br
  = addr_f.label :notes, class: 'form-label'
  br
  = addr_f.text_field :notes, class: 'form-control'
  br
  = addr_f.label :postal_code, class: 'form-label'
  br
  = addr_f.text_field :postal_code, class: 'form-control'
  br
  = addr_f.label :city, class: 'form-label'
  br
  = addr_f.text_field :city, class: 'form-control'
  br

app/views/shared/_navbar.html.slim
nav.navbar.navbar-toggleable-md.navbar-inverse.bg-light.bg-nav.fixed-top
  button.navbar-toggler.navbar-toggler-right aria-controls="navbar" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbar" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  = link_to 'Placeholder Name', root_path, class: 'navbar-brand'
  #navbar.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to 'Home', root_path
      - if user_signed_in?
        li.nav-item 
          = link_to 'Games', root_path
        li.nav-item 
          = link_to 'Tutorial', root_path
        li.nav-item
          = link_to 'My Refs', profile_list_path(current_user.official_association)
        li.nav-item.dropdown
          a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="/" 
            | My Account
          .dropdown-menu aria-labelledby="navbar"
            = link_to 'Availability', root_path, class: 'dropdown-item'
            = link_to 'Preferences', root_path, class: 'dropdown-item'
            = link_to 'Profile', profile_edit_path(current_user), class: 'dropdown-item'
      - else
        li.nav-item
          = link_to 'Demo', demo_path
        li.nav-item
          = link_to 'About', about_path
        li.nav-item
          = link_to 'Contact', contact_path
    ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        li
          = link_to 'Log Out', destroy_user_session_path, method: :delete
        = form_tag('/search', method: 'get', class: 'form-inline mt-2 mt-md-0')
          = text_field_tag(:query, nil, placeholder: 'Search', class: 'form-control mr-sm-2')
          = button_tag('Search', class: 'btn btn-outline-success my-2 my-sm-0', name: nil)
      - else
        li 
          = link_to 'Register', new_user_registration_path
        li
          = link_to 'Log In', new_user_session_path